services:

  postgres:
    image: postgres:17

    container_name: taskflow-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: taskflow_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: taskflow-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres

volumes:
  postgres_data: